version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: careerquest_db
      POSTGRES_USER: cq_user
      POSTGRES_PASSWORD: cq_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=careerquest_db
      - DB_USER=cq_user
      - DB_PASS=cq_password
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
