# Generated by Django 5.2.13 on 2026-05-11 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Niveau')),
                ('current_xp', models.PositiveIntegerField(default=0, verbose_name='XP Actuel')),
                ('appearance', models.CharField(choices=[('NOOB', 'Novice (T-shirt simple)'), ('INT', 'Intermediaire (Chemise)'), ('PRO', 'Expert (Costume/Armure)')], default='NOOB', max_length=4, verbose_name='Apparence visuelle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
