# Generated by Django 5.2.13 on 2026-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la mission')),
                ('description', models.TextField(verbose_name='Description detaillee')),
                ('quest_type', models.CharField(choices=[('PRJ', 'Projet'), ('FRM', 'Formation'), ('CRT', 'Certification')], default='PRJ', max_length=3, verbose_name='Type')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name="Points d'experience (XP)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
